print("======")
print("Score:")
print("======")

Foundation_English = float(input("Foundation English:"))
General_Business = float(input("General Business:"))
Introduction_to_Computer_Systems = float(input("Introduction to Computer systems:"))
Computer_Programming = float(input("Computer Programming:"))
print("============")
print("Final Score:")
print("============")
print("Foundation English:",Foundation_English)
print("General Business:",General_Business)
print("Introduction to Computer systems:",Introduction_to_Computer_Systems)
print("Computer Programming:",Computer_Programming)